openapi: "3.0.3"
info:
  title: "TODO App"
  version: "1.0.0"
  description: "A simple TODO app with FastAPI"
  servers:
    - url: https://your-app-url.com
paths:
  /.well-known/ai-plugin.json:
    get:
      tags:
        - ".well-known"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: object
  /todos/:
    get:
      tags:
        - "todos"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TodoItem"
    post:
      tags:
        - "todos"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoItem"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: integer
  /todos/{todo_id}:
    get:
      tags:
        - "todos"
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodoItem"
    delete:
      tags:
        - "todos"
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "OK"
components:
  schemas:
    TodoItem:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
      required:
        - title
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
