openapi: 3.0.0
info:
  title: Todo app
  description: A todo app for managing your tasks
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /todos/:
    post:
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          description: Todo created successfully
    get:
      summary: Get all todos
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
  /todos/{todo_id}:
    get:
      summary: Get a todo by ID
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Todo found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
    delete:
      summary: Delete a todo by ID
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Todo deleted successfully
        '404':
          description: Todo not found
components:
  schemas:
    Todo:
      type: object
      properties:
        todo_id:
          type: integer
        title:
          type: string
        description:
          type: string
